# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

container: "library://kevinrue/cncb/cncb-2:latest"

configfile: "config/config.yaml"

##### load rules #####

include: "rules/common.smk"
include: "rules/alevin.smk"
include: "rules/downloads.smk"
include: "rules/reports.smk"

##### main rule #####
rule all:
    input:
        expand("results/alevin-reports/{sample}.html", sample=SAMPLES['sample_name'].unique()),
        "results/sce/all.rds",
        "results/hdf5/all-assays.rds",
        "results/hdf5/all-se.rds",
