# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

#container: "library://kevinrue/cncb/cncb-2:latest"
container: "docker://continuumio/miniconda3:24.9.2-0"

configfile: "config/config.yaml"

##### load rules #####

include: "rules/common.smk"
include: "rules/gtf.smk"
include: "rules/downloads.smk"
include: "rules/r.smk"
include: "rules/reports.smk"
include: "rules/simpleaf.smk"

##### main rule #####
rule all:
    input:
        "results/reports/simpleaf.html",
        expand("results/reports/simpleaf/{sample}.html", sample=SAMPLES['sample_name'].unique()),
        "results/reports/emptyDrops.html",
        expand("results/reports/emptyDrops/{sample}.html", sample=SAMPLES['sample_name'].unique()),
        expand("results/reports/barcodeRanks/{sample}.html", sample=SAMPLES['sample_name'].unique()),
        "results/reports/umap.html",
        "results/reports/enrichgo/hvgs.html",
        "results/hdf5/counts",
        "resources/gtf/duplicated_gene_models.tsv",
        expand("results/barcodeRanks/{sample}.rds", sample=SAMPLES['sample_name'].unique()),
        expand("results/simpleaf/lower/{sample}.txt", sample=SAMPLES['sample_name'].unique()),
