channels:
  - conda-forge
  - bioconda
dependencies:
  - alevin-fry
  - bioconductor-biocparallel
  - bioconductor-biocsingular
  - bioconductor-bluster
  - bioconductor-clusterprofiler
  - bioconductor-dropletutils
  - bioconductor-hdf5array
  - bioconductor-fishpond
  - bioconductor-org.dm.eg.db
  - bioconductor-rtracklayer
  - bioconductor-scater
  - bioconductor-scran
  - bioconductor-scuttle
  - bioconductor-summarizedexperiment
  - bioconductor-singlecellexperiment
  - bwa
  - conda
  - fastqc
  - gatk4
  - kb-python
  - mamba
  - multiqc
  - picard
  - piscem
  - r-biocmanager
  - r-cowplot
  - r-ggplot2
  - r-ggrastr
  - r-scales
  - r-stringr
  - r-tidyverse
  - samtools
  - simpleaf
