---
title: "Index page"
author: "Kevin Rue"
date: "`r Sys.Date()`"
output: html_document
---

```{r libraries, include=FALSE}
library(tidyverse)
```

```{r snakemake, include=FALSE}
if (interactive()) {
  report_paths <- c(
    "reports/packages_r.html",
    file.path("reports/fishpond", list.files("../reports/fishpond/"))
  )
} else {
  report_paths <- snakemake@input
}
report_paths <- str_remove(report_paths, "reports/")
```

## Software environment

```{r, echo=FALSE, results='asis'}
path_all <- grep("packages_r.html", report_paths, value = TRUE)
cat(sprintf("- [R packages](%s)", path_all), sep = "\n")
```

## fishpond

The [fishpond](https://www.bioconductor.org/packages/release/bioc/html/fishpond.html) Bioconductor package was used to import the quantification files produced by [simpleaf](https://simpleaf.readthedocs.io/en/latest/).

```{r, echo=FALSE, results='asis'}
path_all <- grep("fishpond.html", report_paths, value = TRUE)
cat(sprintf("- [All samples](%s)", path_all), sep = "\n")
```

<details>
  <summary>Individual samples</summary>
```{r, echo=FALSE, results='asis'}
path_samples <- grep("fishpond/", report_paths, value = TRUE)
names(path_samples) <- fs::path_ext_remove(basename(path_samples))
cat(sprintf("- [%s](%s)", names(path_samples), path_samples), sep = "\n")
```
</details>

## Barcode ranks

<details>
  <summary>Individual samples</summary>
```{r, echo=FALSE, results='asis'}
path_samples <- grep("barcodeRanks/", report_paths, value = TRUE)
names(path_samples) <- fs::path_ext_remove(basename(path_samples))
cat(sprintf("- [%s](%s)", names(path_samples), path_samples), sep = "\n")
```
</details>
