---
title: "Markers"
output: html_document
author: "Kevin Rue"
date: "`r Sys.Date()`"
---

```{r libraries, include=FALSE}
library(cowplot)
library(ggrastr)
library(iSEE)
library(scales)
library(SingleCellExperiment)
library(tidyverse)
```

```{r setup, include=FALSE}
NA
```

```{r snakemake, include=FALSE}
logcounts_file <- snakemake@input[["logcounts"]]
umap_file <- snakemake@input[["umap"]]
#logcounts_file <- "results/filter_mitochondria/_logcounts.rds"
#umap_file <- "results/fastmnn/umap.rds"
```

## Load log-normalised counts

```{r load_markers, echo=FALSE}
sce <- readRDS(logcounts_file)
sce
```

## Load gene sets

```{r load_gmt, echo=FALSE}
gmt_data <- readLines("config/custom_markers.gmt") %>%
  str_split("\t")
markers_list <- list()
for (i in seq_len(length(gmt_data))) {
  markers_list[[gmt_data[[i]][1]]] <- gmt_data[[i]][3:length(gmt_data[[i]])]
}
lengths(markers_list)
```

```{r subset_sce, echo=FALSE}
sce <- sce[rowData(sce)[["gene_name"]] %in% unlist(markers_list), ]
```

## Load UMAP coordinates

```{r load_umap, echo=FALSE}
sce_umap <- readRDS(umap_file)
sce_umap
```

```{r add_umap, echo=FALSE}
reducedDim(sce, "UMAP") <- reducedDim(sce_umap, "UMAP")[colnames(sce), ]
rm(sce_umap)
sce
```

## Plots

```{r, echo=FALSE}
keep <- subsetPointsByGrid(X = reducedDim(sce, "UMAP")[, 1], Y = reducedDim(sce, "UMAP")[, 2], resolution = 400)
sce <- sce[, keep]
```

<!-- Plots below were visually downsampled to `r format(nrow(sce), big.mark = ",")` data points to speed up plotting. -->

<!-- This was achieved using the `iSEE::subsetPointsByGrid()` function with a resolution value of `300`. -->

```{r markers_plots, echo=FALSE, fig.height=5, fig.width=12, results='asis'}
for (marker_group in names(markers_list)) {
  for (marker_name in markers_list[[marker_group]]){
    if (!marker_name %in% rowData(sce)[["gene_name"]]) {
      cat("Skipping: ", marker_name, " not in rowData.", "\n", sep = "")
      next
    }
    marker_id <- rowData(sce) %>%
      as_tibble() %>%
      filter(gene_name == marker_name) %>%
      pull(gene_id)
    if (length(marker_id) > 1) {
      cat("Skipping: ", marker_name, " matched more than one gene ID.", "\n", sep = "")
      next
    }
    cat(sprintf("%s | %s (%s)\n", marker_id, marker_name, marker_group))
    plot_data <- reducedDim(sce, "UMAP") %>%
      as_tibble() %>%
      mutate(
        logcounts = as.numeric(assay(sce, "logcounts")[marker_id, ])
      ) %>%
      bind_cols(
        colData(sce) %>% as_tibble()
      )
    nonzero_quantile_cap <- plot_data %>% filter(logcounts > 0) %>% pull(logcounts) %>% quantile(0.99)
    gg_scatter <- ggplot(plot_data) +
      geom_point(aes(UMAP1, UMAP2, colour = logcounts), size = 0.001) +
      scale_colour_viridis_c(limits = c(0, nonzero_quantile_cap), oob = squish) +
      labs(
        title = paste0(marker_id, " | ", marker_name, " (", marker_group, ")"),
        subtitle = sprintf("Integrated data (logcount cap: %.1f)", nonzero_quantile_cap)
      ) +
      theme_bw()
    gg_histogram <- ggplot() +
      geom_histogram(aes(x = logcounts), data = plot_data, colour = "black", fill = "grey", binwidth = 0.1, linewidth = 0.1) +
      geom_vline(xintercept = nonzero_quantile_cap, colour = "black", linewidth = 0.5, linetype = "dashed") +
      labs(
        title = sprintf("%s | %s (%s)", marker_id, marker_name, marker_group),
        subtitle = sprintf("Integrated data (99%% non-zero quantile: %.1f)", nonzero_quantile_cap)
      ) +
      theme_bw()
    cowplot_all <- plot_grid(gg_scatter, gg_histogram, nrow = 1)
    print(cowplot_all)
  }
}
```

## Session info

`r date()`

Bioconductor version `r BiocManager::version()`

```{r session_info, echo=FALSE}
sessionInfo()
```
