---
title: "emptyDrops (sample)"
output: html_document
author: "Kevin Rue"
date: "`r Sys.Date()`"
---

```{r libraries, include=FALSE}
library(ggrastr)
library(S4Vectors)
library(SummarizedExperiment)
library(scales)
library(tidyverse)
```

```{r constants, include=FALSE}
umi_breaks <- 10^(-1:10)
umi_minor_breaks <- rep(c(1, 2, 5), 12) * (10^rep(-1:10, each = 3))
barcode_breaks <- 10^(-1:10)
barcode_minor_breaks <- 10^rep(-1:10)
```

```{r snakemake, include=FALSE}
rds_file <- snakemake@input[["rds"]]
```

## Run parameters

```{r parameters, echo=FALSE}
format_bold <- function(x) sprintf("**%s**", x)
df <- matrix(
  data = c(
    format_bold("Input file"), rds_file
  ),
  ncol = 2, byrow = TRUE
)
knitr::kable(x = df)
```

## Load emptyDrops results

### Table

```{r read_rds, echo=FALSE}
#| message: false
emptydrops_results <- readRDS(rds_file)
emptydrops_results
```

### Metadata

```{r metadata, echo=FALSE}
emptydrops_metadata <- metadata(emptydrops_results)
format_bold <- function(x) sprintf("**%s**", x)
df <- matrix(
  data = c(
    format_bold("retain (UMI)"), format(emptydrops_metadata[["retain"]], big.mark = ","),
    format_bold("lower (UMI)"), format(emptydrops_metadata[["lower"]], big.mark = ","),
    format_bold("niters"), format(emptydrops_metadata[["niters"]], big.mark = ","),
    format_bold("alpha"), format(emptydrops_metadata[["alpha"]], big.mark = ","),
    format_bold("ignore (UMI)"), format(emptydrops_metadata[["ignore"]], big.mark = ",")
  ),
  ncol = 2, byrow = TRUE
)
knitr::kable(x = df)
```

## Overall statistics

```{r filter_stats_table, echo=FALSE}
fdr_thresholds <- c(0.01, 0.001, 0.0001, 0.00001)
filter_stats <- tibble(
    threshold = fdr_thresholds,
    barcodes = vapply(fdr_thresholds, function(x) sum(emptydrops_results$FDR < x, na.rm = TRUE), integer(1))
)
knitr::kable(filter_stats)
```

## Plot

- <span style="color:green">Green (retain)</span>: UMI count above which barcodes are retained.
- <span style="color:red">Red (ignore)</span>: UMI count below which barcodes are not tested.
- <span style="color:grey">Grey (lower)</span>: UMI count below which barcodes are used to compute the ambient profile. 

```{r barcode_rank, echo=FALSE}
emptydrops_results <- emptydrops_results %>%
  as.data.frame() %>% 
  as_tibble() %>% 
  filter(Total > 0) %>% 
  arrange(desc(Total)) %>% 
  mutate(Rank = row_number())
```

```{r barcode_rank_color_fdr_plots, echo=FALSE, fig.height=5, fig.width=7}
fdr_thresholds <- c(0.01, 0.001, 0.0001, 0.00001)
for (fdr_cutoff in fdr_thresholds) {
    gg <- emptydrops_results %>% 
        mutate(
            cell = factor(FDR < fdr_cutoff, c(TRUE, FALSE, NA), c("Cell", "Empty"))
        ) %>%
        ggplot(aes(Rank, Total)) +
        geom_hline(yintercept = emptydrops_metadata[["retain"]], linetype = "dashed", color = "green", linewidth = 0.5) +
        geom_hline(yintercept = emptydrops_metadata[["ignore"]], linetype = "dashed", color = "red", linewidth = 0.5) +
        geom_hline(yintercept = emptydrops_metadata[["lower"]], linetype = "dashed", color = "grey", linewidth = 0.5) +
        geom_point_rast(aes(color = cell), size = 0.1) +
        # geom_point(aes(color = cell), size = 0.1) +
        scale_x_log10(breaks = barcode_breaks, minor_breaks = barcode_minor_breaks, labels = label_number(scale_cut = cut_short_scale())) +
        scale_y_log10(breaks = umi_breaks, minor_breaks = umi_minor_breaks, labels = label_number(scale_cut = cut_short_scale())) +
        facet_wrap(~ cell) +
        theme_bw() +
        labs(
            y = "UMI Counts",
            x = "Barcodes",
            subtitle = paste0("FDR threshold: ", fdr_cutoff)
        ) +
        guides(color = "none")
    print(gg)
}
```

## Session info

`r date()`

Bioconductor version `r BiocManager::version()`

```{r session_info, echo=FALSE}
sessionInfo()
```
