---
title: "Mitochondrial content (sample)"
output: html_document
author: "Kevin Rue"
date: "`r Sys.Date()`"
---

```{r libraries, include=FALSE}
library(SingleCellExperiment)
library(tidyverse)
```

```{r setup, include=FALSE}
umi_breaks <- 10^(-1:10)
umi_minor_breaks <- rep(c(1, 2, 5), 12) * (10^rep(-1:10, each = 3))
barcode_breaks <- 10^(-1:10)
barcode_minor_breaks <- 10^rep(-1:10)
```

```{r snakemake, include=FALSE}
rds_file <- snakemake@input[["rds"]]
```

```{r sample, include=FALSE}
sample_name <- fs::path_ext_remove(basename(rds_file))
```

## Run parameters

```{r parameters, echo=FALSE}
format_bold <- function(x) sprintf("**%s**", x)
df <- matrix(
  data = c(
    format_bold("Input file"), rds_file
  ),
  ncol = 2, byrow = TRUE
)
knitr::kable(x = df)
```


## Load sample data

```{r sce, echo=FALSE}
sce <- readRDS(rds_file)
sce
```

## Load mitochondrial genes

```{r mito_gene_table, echo=FALSE}
mito_gene_table <- readr::read_tsv("config/mitochdondrial_genes.tsv", show_col_types = FALSE)
mito_gene_table
```

## Barcode statistics

```{r compute_statistics, include=FALSE}
barcode_stats <- tibble(
  umi_sum = colSums(assay(sce, "counts")),
  genes = colSums(assay(sce, "counts") > 0),
  mt_pct = colSums(assay(sce, "counts")[mito_gene_table[["gene_id"]], ]) / umi_sum
) %>% 
  filter(umi_sum > 0) %>% 
  arrange(desc(umi_sum)) %>% 
  mutate(rank_umi = row_number()) %>% 
  arrange(desc(genes)) %>% 
  mutate(rank_genes = row_number())
barcode_stats
rm(sce)
```

## Plot

```{r histogram, echo=FALSE}
barcode_stats %>% 
  ggplot(aes(x = mt_pct)) +
  geom_histogram(binwidth = 0.01, color = "black", fill = "grey") +
  coord_cartesian(xlim = c(0, 1)) +
  # scale_y_log10(breaks = umi_breaks, minor_breaks = umi_minor_breaks, labels = label_number(scale_cut = cut_short_scale())) +
  theme_bw() +
  labs(
    y = "Barcodes",
    x = "Mitochondrial content",
    subtitle = sample_name
  )
```

## Session info

`r date()`

Bioconductor version `r BiocManager::version()`

```{r session_info, echo=FALSE}
sessionInfo()
```
