---
title: "UMAP (after fastMNN integration)"
output: html_document
author: "Kevin Rue"
date: "`r Sys.Date()`"
---

```{r libraries, include=FALSE}
library(BiocSingular)
library(ggrastr)
library(SingleCellExperiment)
library(stringr)
library(tidyverse)
```

```{r setup, include=FALSE}
NA
```

```{r snakemake, include=FALSE}
rds_file <- snakemake@input[["rds"]]
```

## Load SingleCellExperiment object

```{r load_sce, echo=FALSE}
sce <- readRDS(rds_file)
sce
```

## Plots

```{r umap-coloured, echo=FALSE, fig.width=9, fig.height=7}
for (coldata in "batch") {
  gg_data <- reducedDim(sce, "UMAP") %>%
    as_tibble() %>%
    mutate(
      COLOUR = colData(sce)[[coldata]]
    ) %>%
    slice_sample(prop = 1)
  gg_label_data <- gg_data %>%
    group_by(COLOUR) %>%
    summarise(across(everything(), mean))
  gg <- ggplot() +
  rasterise(
    geom_point(aes(UMAP1, UMAP2, colour = COLOUR), gg_data, size = 0.001),
    dpi = 300, scale = 0.5
  ) +
    geom_text(aes(UMAP1, UMAP2, label = COLOUR), gg_label_data) +
    theme_bw() +
    labs(
      colour = coldata
    ) +
    guides(
      color = guide_legend(override.aes = list(size = 5))
    )
  print(gg)
}
```

## Session info

`r date()`

Bioconductor version `r BiocManager::version()`

```{r session_info, echo=FALSE}
sessionInfo()
```
