---
title: "UMAP (merged - no integration)"
output: html_document
author: "Kevin Rue"
date: "`r Sys.Date()`"
---

```{r libraries, include=FALSE}
library(ggrastr)
library(SingleCellExperiment)
library(stringr)
library(tidyverse)
```

```{r setup, include=FALSE}
NA
```

```{r snakemake, include=FALSE}
rds_file <- snakemake@input[["rds"]]
```

## Load SingleCellExperiment object

```{r load_sce, echo=FALSE}
sce <- readRDS(rds_file)
sce
```

## Add barcode metadata to SingleCellExperiment object
```{r sample_metadata_table, echo=FALSE, message=FALSE}
# per-sample metadata
sample_metadata_table <- read_tsv("config/samples.tsv") %>%
  column_to_rownames("sample_name")
# names and levels of metadata factors
metadata_barcodes_factor <- yaml::read_yaml("config/config.yaml")[["metadata"]][["barcodes"]][["factor"]]
# set levels
for (factor_name in names(metadata_barcodes_factor)) {
  if (! factor_name %in% colnames(sample_metadata_table)) {
    stop(sQuote(factor_name), " is not a column in sample metadata")
  }
  new_factor <- factor(sample_metadata_table[[factor_name]], levels = metadata_barcodes_factor[[factor_name]])
  sample_metadata_table[[factor_name]] <- new_factor
}
# add to colData
colData(sce) <- cbind(
  colData(sce),
  sample_metadata_table[colData(sce)[["sample"]], names(metadata_barcodes_factor)]
)
colData(sce)[, names(metadata_barcodes_factor)] %>%
  as.data.frame() %>%
  as_tibble()
```

## Plots

```{r umap-coloured, echo=FALSE, fig.width=7, fig.height=5}
for (coldata in names(metadata_barcodes_factor)) {
  gg_data <- reducedDim(sce, "UMAP") %>%
    as_tibble() %>%
    mutate(
      COLOUR = colData(sce)[[coldata]]
    ) %>%
    slice_sample(prop = 1)
  gg_label_data <- gg_data %>%
    group_by(COLOUR) %>%
    summarise(across(everything(), mean))
  gg <- ggplot() +
    geom_point_rast(aes(UMAP1, UMAP2, colour = COLOUR), gg_data, size = 0.05) +
    geom_text(aes(UMAP1, UMAP2, label = COLOUR), gg_label_data) +
    theme_bw() +
    labs(
      colour = coldata
    ) +
    guides(
      color = guide_legend(override.aes = list(size = 5))
    )
  print(gg)
}
```

## Session info

`r date()`

Bioconductor version `r BiocManager::version()`

```{r session_info, echo=FALSE}
sessionInfo()
```
