---
title: "scDblFinder (sample)"
output: html_document
author: "Kevin Rue"
date: "`r Sys.Date()`"
---

```{r libraries, include=FALSE}
library(ggrastr)
library(SingleCellExperiment)
library(tidyverse)
```

```{r constants, include=FALSE}
umi_breaks <- 10^(-1:10)
umi_minor_breaks <- rep(c(1, 2, 5), 12) * (10^rep(-1:10, each = 3))
barcode_breaks <- 10^(-1:10)
barcode_minor_breaks <- 10^rep(-1:10)
```

```{r snakemake, include=FALSE}
if (interactive()) {
  rds_sce_dbl <- "../results/scdblfinder/result/WPPp000hrs_rep2.rds"
  rds_sce <- "../results/before_scdblfinder/WPPp000hrs_rep2.rds"
} else {
  rds_sce_dbl <- snakemake@input[["scdblfinder"]]
  rds_sce <- snakemake@input[["sce"]]
}
```

## Run parameters

```{r parameters, echo=FALSE}
format_bold <- function(x) sprintf("**%s**", x)
df <- matrix(
  data = c(
    format_bold("SCE (doublets"), rds_sce_dbl,
    format_bold("SCE (before)"), rds_sce
  ),
  ncol = 2, byrow = TRUE
)
knitr::kable(x = df)
```

## Load scDblFinder results

### Table

```{r load_scdblfinder, echo=FALSE}
sce_dbl <- readRDS(rds_sce_dbl)
sce_dbl
```

### Metadata

```{r metadata, echo=FALSE}
scdblfinder_metadata <- metadata(sce_dbl)
format_bold <- function(x) sprintf("**%s**", x)
df <- matrix(
  data = c(
    format_bold("scDblFinder.threshold"), format(scdblfinder_metadata[["scDblFinder.threshold"]])
  ),
  ncol = 2, byrow = TRUE
)
knitr::kable(x = df)
```

## Overall statistics

```{r filter_stats_table, echo=FALSE}
format_bold <- function(x) sprintf("**%s**", x)
df <- matrix(
  data = c(
    format_bold("Input barcodes"), format(sum(sce_dbl$src == "real"), big.mark = ","),
    format_bold("Artificial doublets"), format(sum(sce_dbl$src == "artificial"), big.mark = ","),
    format_bold("Predicted singlets"), format(sum(sce_dbl$type == "real" & sce_dbl$class == "singlet"), big.mark = ","),
    format_bold("Predicted doublets"), format(sum(sce_dbl$type == "real" & sce_dbl$class == "doublet"), big.mark = ",")
  ),
  ncol = 2, byrow = TRUE
)
knitr::kable(x = df)
```

## Histogram of scDblFinder scores

```{r plot, echo=FALSE, fig.width=7, fig.height=5}
ggplot_data <- colData(sce_dbl) %>% 
  as.data.frame() %>% 
  as_tibble()
ggplot_data %>% 
  filter(type == "real") %>% 
  ggplot() +
  geom_histogram(
    mapping = aes(x = score),
    breaks = seq(0, 1, 0.01),
    colour = "black", fill = "grey"
  ) +
  facet_wrap(~class, ncol = 1) +
  scale_x_continuous(limits = c(0, 1)) +
  theme_bw() +
  labs(
    y = "Barcodes",
    x = "Score (scDblFinder)"
  )
```

## Overlay predicted doublets on UMAP layout

### Inport UMAP layout

```{r load_sce, echo=FALSE}
sce <- readRDS(rds_sce)
sce
```

### Plot

```{r umap_overlaid, echo=FALSE, fig.width=7, fig.height=5}
plot_data <- reducedDim(sce, "UMAP") %>% as("DataFrame")
plot_data <- cbind(plot_data, colData(sce_dbl)[rownames(plot_data), ])
ggplot() +
  rasterise(
    geom_point(
      mapping = aes(x = UMAP1, y = UMAP2),
      data = plot_data %>% as_tibble() %>% filter(class == "singlet"),
      size = 0.01, colour = "cyan3"
    ),
    dpi = 300
  ) +
  rasterise(
    geom_point(
      mapping = aes(x = UMAP1, y = UMAP2),
      data = plot_data %>% as_tibble() %>% filter(class == "doublet"),
      size = 0.01, colour = "brown1"
    ),
    dpi = 300
  ) +
  labs(
    x = "UMAP1",
    y = "UMAP2"
  ) +
  guides(
    colour = guide_legend(override.aes = list(size = 5))
  ) +
  theme_bw()
```

```{r umap_facet, fig.width=12, fig.height=5}
ggplot() +
  rasterise(
    geom_point(
      mapping = aes(x = UMAP1, y = UMAP2, colour = class),
      data = plot_data %>% as_tibble() %>% slice_sample(prop = 1),
      size = 0.01
    ),
    dpi = 300
  ) +
  facet_wrap(~ class) +
  labs(
    x = "UMAP1",
    y = "UMAP2"
  ) +
  guides(
    colour = guide_legend(override.aes = list(size = 5))
  ) +
  theme_bw()
```


## Session info

`r date()`

Bioconductor version `r BiocManager::version()`

```{r session_info, echo=FALSE}
sessionInfo()
```
