---
title: "Individual sample quality control"
output: html_document
author: "Kevin Rue"
date: "`r Sys.Date()`"
---

## Sample information

- Name: `r basename(snakemake@input[["sce"]])`

```{r libraries, include=FALSE}
library(cowplot)
library(fishpond)
library(ggplot2)
library(rtracklayer)
library(scales)
library(stringr)
library(SummarizedExperiment)
library(tidyverse)
umi_breaks <- 10^(-1:10)
umi_minor_breaks <- rep(c(1, 2, 5), 12) * (10^rep(-1:10, each = 3))
barcode_breaks <- 10^(-1:10)
barcode_minor_breaks <- 10^rep(-1:10)
```

```{r parameters, include=FALSE}
umi_cutoff <- snakemake@params[["umi_cutoff"]]
```

## Load sampleaf output

- Output format: `S+A`

```{r load_fry, echo=FALSE}
#| message: false
sce <- readRDS(snakemake@input[["sce"]])
sce
```

## Barcode statistics

```{r compute_statistics, include=FALSE}
barcode_stats <- tibble(
  umi_sum = colSums(assay(sce, "counts")),
  genes = colSums(assay(sce, "counts") > 0)
) %>% 
  filter(umi_sum > 0) %>% 
  arrange(desc(umi_sum)) %>% 
  mutate(rank_umi = row_number()) %>% 
  arrange(desc(genes)) %>% 
  mutate(rank_genes = row_number())
barcode_stats
rm(sce)
```

### Range of UMI per barcode

```{r range_umi_sum, include=FALSE}
range(barcode_stats$umi_sum)
```

### Barcode-Rank Plot

```{r barcode_rank_plot, echo=FALSE}
filtered_stats <- barcode_stats %>% 
  filter(umi_sum > 0) %>% 
  summarise(
    barcodes = sum(umi_sum >= umi_cutoff),
  )
top_stats <- barcode_stats %>%
  slice_max(umi_sum, n = 1)
ggplot(barcode_stats, aes(x = rank_umi, y = umi_sum)) +
  geom_line() +
  geom_label(aes(label = format(umi_sum, big.mark = ",")), data = top_stats, alpha = 0.5, hjust = 0) +
  geom_hline(yintercept = umi_cutoff, linetype = "dashed", linewidth = 0.5, colour = "red") +
  geom_vline(aes(xintercept = barcodes), data = filtered_stats, linetype = "dashed", linewidth = 0.5, colour = "red") +
  geom_label(aes(x = barcodes, y = 1, label = format(barcodes, big.mark = ",")), filtered_stats, colour = "red", vjust = 0) +
  scale_x_log10(breaks = barcode_breaks, minor_breaks = barcode_minor_breaks, labels = label_number(scale_cut = cut_short_scale())) +
  scale_y_log10(breaks = umi_breaks, minor_breaks = umi_minor_breaks, labels = label_number(scale_cut = cut_short_scale())) +
  theme_bw() +
  labs(
    y = "UMI Counts",
    x = "Barcodes",
    title = paste0("Maximum UMI count & Number of barcodes >= ", format(umi_cutoff, big.mark = ","), " UMIs")
  )
```

### Histogram of UMI per barcode

```{r umi_sum_histogram, echo=FALSE, fig.width=12, fig.height=4}
gg1 <- ggplot(barcode_stats, aes(x = umi_sum)) +
  geom_histogram(binwidth = 100) +
  scale_x_continuous(labels = label_number(scale_cut = cut_short_scale())) +
  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) +
  labs(title = "Full view") +
  theme_bw() +
  labs(
    y = "Barcodes",
    x = "UMI Counts"
  )
gg2 <- ggplot(barcode_stats, aes(x = umi_sum)) +
  geom_histogram(binwidth = 100) +
  geom_vline(xintercept = umi_cutoff, color = "red", linetype = "dashed") +
  scale_x_continuous(labels = label_number(scale_cut = cut_short_scale())) +
  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) +
  coord_cartesian(xlim = c(0, 5E3)) +
  labs(title = "Total UMI (0 - 5,000)") +
  theme_bw() +
  labs(
    y = "Barcodes",
    x = "UMI Counts"
  )
gg3 <- ggplot(barcode_stats, aes(x = umi_sum)) +
  geom_histogram(binwidth = 100) +
  geom_vline(xintercept = umi_cutoff, color = "red", linetype = "dashed") +
  scale_x_continuous(labels = label_number(scale_cut = cut_short_scale())) +
  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) +
  coord_cartesian(xlim = c(0, 5E3), ylim = c(0, 5E3)) +
  labs(title = "Total UMI (0 - 5,000) & Bin count (0 - 5,000)") +
  theme_bw() +
  labs(
    y = "Barcodes",
    x = "UMI Counts"
  )
gg4 <- ggplot(barcode_stats, aes(x = umi_sum)) +
  geom_histogram(binwidth = 100) +
  scale_x_continuous(labels = label_number(scale_cut = cut_short_scale())) +
  coord_cartesian(xlim = c(5E3, NA), ylim = c(0, 100)) +
  labs(title = "Total UMI (5,000 - max) & Bin count (0 - 100)") +
  theme_bw() +
  labs(
    y = "Barcodes",
    x = "UMI Counts"
  )
plot_grid(gg1, gg2, gg3, gg4)
rm(gg1, gg2, gg3, gg4)
```

## Session info

Bioconductor version `r BiocManager::version()`

```{r session_info, echo=FALSE}
sessionInfo()
```
