genome:
  fastas:
    - https://ftp.ensembl.org/pub/release-113/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.46.dna.primary_assembly.2L.fa.gz
    - https://ftp.ensembl.org/pub/release-113/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.46.dna.primary_assembly.2R.fa.gz
    - https://ftp.ensembl.org/pub/release-113/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.46.dna.primary_assembly.3L.fa.gz
    - https://ftp.ensembl.org/pub/release-113/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.46.dna.primary_assembly.3R.fa.gz
    - https://ftp.ensembl.org/pub/release-113/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.46.dna.primary_assembly.4.fa.gz
    - https://ftp.ensembl.org/pub/release-113/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.46.dna.primary_assembly.X.fa.gz
    - https://ftp.ensembl.org/pub/release-113/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.46.dna.primary_assembly.Y.fa.gz
    - https://ftp.ensembl.org/pub/release-113/fasta/drosophila_melanogaster/dna/Drosophila_melanogaster.BDGP6.46.dna.primary_assembly.mitochondrion_genome.fa.gz
  gtf: https://ftp.ensembl.org/pub/release-113/gtf/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.46.113.gtf.gz

metadata:
  barcodes:
    factor:
      timepoint:
        - m048hrs
        - m024hrs
        - p000hrs
        - p024hrs
        - p048hrs
        - p072hrs
        - p096hrs
        - p120hrs
      replicate:
        - 1
        - 2

simpleaf:
  index:
    rlen: 150

emptydrops:
  lower: 500
  niters: 10000
  fdr: 0.001

filters:
  barcodes:
    mt_pct_max: 0.25

scdblfinder:
  variable_genes:
    n: 1000
    exclude: config/hvgs_exclude.tsv
  cluster:
    kmeans:
      centers: 1000
      iter_max: 100
    louvain:
      resolutions:
        - 0.1
        - 0.2
        - 0.5
        - 1
        - 2
        - 5
        - 10
    walktrap:
      steps:
        - 4
        - 8
        - 16

variable_genes:
  block: sample
  proportion: 0.1 # TODO: remove
  exclude: config/hvgs_exclude.tsv

fastmnn:
  batch: timepoint
  k: 20
  d: 200
  cluster:
    kmeans:
      centers: 2000
    nn:
      k: 5
  markers:
    block: sample
    lfc: 1
  umap:
    n_pcs: 200

fixed_pca:
  rank: 100

umap:
  n_pcs: 50
